service: xd-pocket-archiver

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-personal
  stage: prod
  region: eu-west-1
  environment:
    # DEBUG: false
    PAGE_LOAD_TIMEOUT: 45000
    LOGGING: true

  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "sqs:SendMessage"
  #       - "sqs:GetQueueUrl"
  #     Resource: "arn:aws:sqs:${self:provider.region}:567406759239:xd-pocket-archive-mainqueue"

  #   - Effect: "Allow"
  #     Action:
  #       - "sqs:ListQueues"
  #     Resource: "arn:aws:sqs:${self:provider.region}:567406759239:*"

plugins:
  - serverless-plugin-chrome
  - serverless-webpack

custom:
  chrome:
    flags:
      - --window-size=1280,1696 # Letter size
      - --hide-scrollbars

functions:
  pdf:
    description: Headless Chrome Serverless-framework PDF example
    memorySize: 1536
    timeout: 120
    handler: src/handlers/pdf.default
    events:
      - http:
          path: pdf
          method: post

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"
    # MainQueue:
    #   Type: "AWS::SQS::Queue"
    #   Properties:
    #     QueueName: "xd-pocket-archive-mainqueue"
    #     VisibilityTimeout: 120

    # Enable X-Ray tracing on Lambda functions
    # ScreenshotLambdaFunction:
    #   Properties:
    #     TracingConfig:
    #       Mode: Active
    # PdfLambdaFunction:
    #   Properties:
    #     TracingConfig:
    #       Mode: Active
